--
# Firewall Control

- name: Enable firewall for Domain, Public and Private profiles
  hosts: all

  gather_facts: false

  tasks:
    - name: Enable firewall for Domain, Public and Private profiles
      win_firewall:
        state: enabled
        profiles:
        - Domain
        - Private
        - Public
      tags: enable_firewall
