- name: Install all security, critical, and rollup updates without a scheduled task
  hosts: all
  
  gather_facts: false
  tasks:
    - name: Win Update
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups